//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasmHosted.Client.Pages.PizzaRestaurant {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PizzaRestaurant2_no {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PizzaRestaurant2_no() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WasmHosted.Client.Pages.PizzaRestaurant.PizzaRestaurant2_no", typeof(PizzaRestaurant2_no).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Loading___ {
            get {
                return ResourceManager.GetString("Loading...", resourceCulture);
            }
        }
        
        internal static string Our_selection_of_pizzas {
            get {
                return ResourceManager.GetString("Our selection of pizzas", resourceCulture);
            }
        }
        
        internal static string Please_enter_your_details_below {
            get {
                return ResourceManager.GetString("Please enter your details below", resourceCulture);
            }
        }
        
        internal static string Welcome_to_Pizza_Restaurant {
            get {
                return ResourceManager.GetString("Welcome to Pizza Restaurant", resourceCulture);
            }
        }
        
        internal static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
    }
}
